# Site settings
title: Randy Parrish
general_email: rndparr@gmail.com
academic_email: randy.parrish@emory.edu

description: > # this means to ignore newlines until "baseurl:"
  Research specialist at Emory University.



# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "/Users/randyparr/github/website"
baseurl: "/website" # the subpath of your site, e.g. /blog/
url: "https://rndparr.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: rndparr
# linkedin_username: linkedin_username
# facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title